name: GitHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
    - name: setup
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      run: |
         command="sudo apt-get -y update && \
                  wget https://github.com/precice/precice/releases/download/v2.2.0/libprecice2_2.2.0_focal.deb && \
                  sudo apt-get -y install ./libprecice2_2.2.0_focal.deb && \
                  git clone https://$ACCESS_TOKEN@github.com/${{ github.repository }} && \
                  cd matrix-free-dealii-precice && \
                  git fetch origin ${{ github.ref }} && \
                  git checkout FETCH_HEAD && \
                  cd tests && \
                  ./run_tests.sh"; 
         
         echo $command

         docker pull dealii/dealii:master-focal
         docker run -t dealii/dealii:master-focal /bin/sh -c "$command";
