name: Heat transfer CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 8 * * 2'  # run once in a week (here Tue at 8am)

jobs:
  build:

    runs-on: ubuntu-latest
    container: dealii/dealii:master-jammy
    timeout-minutes: 30

    steps:
    - name: prepare container
      run: sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install libboost-all-dev
    - name: build preCICE
      uses: precice/setup-precice-action@main
      with:
        precice-version: 3.1.2
        install-prefix: $HOME/local
    - uses: actions/checkout@v4
    - name: run test
      run: cd tests/heat && ./run_tests.sh
