name: Heat transfer CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 8 * * 2'  # run once in a week (here Tue at 8am)

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: dealii/dealii:master-jammy
      options: --user root
    timeout-minutes: 30

    steps:
    - name: prepare container
      run: sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install libboost-all-dev
    - name: build preCICE
      uses: precice/setup-precice-action@main
      with:
        precice-version: develop
    - uses: actions/checkout@v4
    - name: Adjust user rights
      run: cd tests/heat && chown -R dealii .
    - name: run test
      run: sudo -u dealii bash -c "./run_tests.sh"
