name: Heat transfer CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 8 * * 2'  # run once in a week (here Tue at 8am)

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v3
    - name: run test

      run: |
         command="sudo apt-get -y update && \
                  wget https://github.com/precice/precice/releases/download/v2.5.0/libprecice2_2.5.0_focal.deb && \
                  sudo apt-get -y install ./libprecice2_2.5.0_focal.deb && \
                  git clone https://github.com/${{ github.repository }} && \
                  cd matrix-free-dealii-precice && \
                  git fetch origin ${{ github.ref }} && \
                  git checkout FETCH_HEAD && \
                  cd tests/heat && \
                  ./run_tests.sh"; 
         
         echo $command

         docker pull dealii/dealii:master-focal
         docker run -t dealii/dealii:master-focal /bin/sh -c "$command";
